export const CPF_CHANGED = 'CPF_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const PICTURE_CHANGED = 'PICTURE_CHANGED';
export const NAME_CHANGED = 'NAME_CHANGED';
export const SET_USER = 'SET_USER';